<a href="https://colab.research.google.com/github/Tagore-7/Deep_Learning_Projects/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
# intro to tensors
# creating tensor
# scalar tensor
# tenor can be created using torch.tensor
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
# scalar characteristics
# dimension
scalar.ndim

0

In [ ]:
# no dimension single number
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
### Random tensors

#why random tensors?
# random tensors are important because many neural networs learn is that they start with with tensors full of random numbers
# and then adujst those random numbers to better represent the data

# start with random numbers -> look at the data  -> update random numbers -> loom at data -> update random numbers

In [ ]:
# create random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5422, 0.1378, 0.8999, 0.5682],
        [0.1922, 0.7268, 0.7536, 0.9023],
        [0.4138, 0.8998, 0.3845, 0.5522]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor

tensor([[[0.1527, 0.1547, 0.8522],
         [0.2338, 0.8720, 0.0156],
         [0.0655, 0.3991, 0.7054],
         ...,
         [0.1498, 0.7180, 0.7796],
         [0.9708, 0.1327, 0.4454],
         [0.6592, 0.3955, 0.4318]],

        [[0.4195, 0.1217, 0.3932],
         [0.0655, 0.4687, 0.6117],
         [0.8717, 0.2475, 0.3070],
         ...,
         [0.2526, 0.7509, 0.1936],
         [0.0323, 0.8408, 0.2273],
         [0.8325, 0.3726, 0.2368]],

        [[0.8317, 0.9969, 0.4893],
         [0.8174, 0.5618, 0.6173],
         [0.9662, 0.8003, 0.9408],
         ...,
         [0.2511, 0.5318, 0.0135],
         [0.8979, 0.3357, 0.0465],
         [0.6065, 0.9327, 0.0727]],

        ...,

        [[0.4316, 0.8825, 0.5243],
         [0.4360, 0.8116, 0.2855],
         [0.2742, 0.7391, 0.0124],
         ...,
         [0.2302, 0.5972, 0.1814],
         [0.6162, 0.8623, 0.5368],
         [0.6398, 0.2177, 0.8031]],

        [[0.4942, 0.6296, 0.1858],
         [0.1156, 0.1322, 0.2573],
         [0.

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
### Zeros and ones
# create a tensor of all zeros
zeros = torch.zeros(size= (3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tenosr of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
# creating tensors in range
torch.range(0, 10)

<ipython-input-29-7602356ed85b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(1, 10) #new verison

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=0, end = 1000, step = 70)
one_to_ten

tensor([  0,  70, 140, 210, 280, 350, 420, 490, 560, 630, 700, 770, 840, 910,
        980])

In [ ]:
# creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# tensor datatypes
# float 32 tensor
# dtype = what datatype is tensor e.g float32, float 16  # precision in computing single precision floating point fp32
# tensor dataypes is one of the 3 big errors in PyTorch and Deep Learning
# 1. Tensors not right datatype
# 2. Tensors not right shape
# 3. Tensors not on the right device
# device - what device is your tensor is on
# required gradients for deep learning backtracking
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device = None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_32_tensor * float_16_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# getting information from tensors
# tensor.dtype - datatype
# tensor.shape - shape
# tensor.device - device
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9465, 0.0160, 0.3115, 0.6955],
        [0.1729, 0.6126, 0.3924, 0.9627],
        [0.6767, 0.7409, 0.0508, 0.3475]])

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device Tesnor is on: {some_tensor.device}")

tensor([[0.9465, 0.0160, 0.3115, 0.6955],
        [0.1729, 0.6126, 0.3924, 0.9627],
        [0.6767, 0.7409, 0.0508, 0.3475]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device Tesnor is on: cpu


In [1]:
### Manipulating Tensorsd (tensor operations)

# Tensor operations inlcude:
# addition
# subtraction
# multiplication (element-wise)
# division
# matrix multiplication

In [5]:
# create a tensor
tensor = torch.tensor([1, 2,3])
tensor + 10

tensor([11, 12, 13])

In [6]:
# multiplt tensor by 10
tensor * 10

tensor([10, 20, 30])

In [7]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [8]:
# subtraction
tensor = tensor - 10
tensor

tensor([ 0, 10, 20])

In [9]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([  0, 100, 200])

In [10]:
 torch.add(tensor, 10)

tensor([10, 20, 30])

In [12]:
# Multiplication of Matrix
# Two main ways of performing multiplication in neural networks and deep learning
# 1. element - wise multiplication
# 2. multiplying matrix by another matrix (dot product)

# element wise multiplication example
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
Equals: tensor([  0, 100, 400])


In [13]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(500)

In [15]:
# matrix mutlplication by hand
0 * 0 + 10 * 10 + 20 * 20

500

In [16]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 1.97 ms, sys: 66 µs, total: 2.04 ms
Wall time: 4.4 ms


tensor(500)

In [17]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 490 µs, sys: 30 µs, total: 520 µs
Wall time: 346 µs


tensor(500)

In [ ]:
# two main rules of matrix multiplication
# the inner dimensions must match
# (3, 2) @ (2, 3)  will work
# (3, 2) @ (3, 2)  won't work
torch.matmul(torch.rand(2, 3) , torch.rand(3, 2))
# the resulting matrix has the shape of the outer dimensions
# (2, 3) @ (3, 2) ->  (2, 2)
# (3, 2) @ (2, 3) -> (3, 3)
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)
tensor_A.shape, tensor_B.shape
# to fix tensor shape issues we can manipluate the shape of one of the tensors using transpose
# a transpose is the switches the axes or dimensions of a given tensor
tensor_B.T, tensor_B
tensor_B.T.shape, tensor_B.shape
torch.matmul(tensor_A, tensor_B.T)
torch.matmul(tensor_A, tensor_B.T).shape


In [ ]:
# finding the min, max, mean, sum, etc (tensor aggregation)
x = torch.arange(0, 100, 10)
torch.min(x), x.min()
torch.max(x), x.max()
torch.mean(x)
torch.mean(x.type(torch.float32))
# note torch.mean requires a tensor of float 32 datatype to work
torch.sum(x), x.sum()

In [ ]:
# finding the positional min and max
x.argmin(), x.argmax()
# returns index position of tensor where min and max occurs

In [ ]:
# reshaping, stacking, squeezing and unsqueezing tensor
# reshaping - reshape an input tensor to a defined shape
# view - return a view of an input tensor of certain shape but keep the same memory as the orignal tensor
# stacking - combine multiple tensors on top of each other (vstack) (hstack)
# Squeeze - removes all '1' dimension from a tensor
# Unsqueeze - add a '1' dimension to a target tensor
# permute - return a view of the input with dimensions permuted in a certain way

x = torch.arange(1, 10)
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

x = torch.arange(1, 10)
x_reshaped = x.reshpe(2, 5)

# change the view
z = x.view(1, 9)
z.shape
# changing z changes x ( because a view of a tensor shares the same memory as the orignal memory of x)

# stacking
# stack tensor on top of each other
x_stacked = torch.stack([x, x, x,x], dim = 0)
x_stacked

x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

# Squeeze
x_squeeze = torch.squeeze(x)
# removes all single dimensions

# unsqueeze
x_unsqueeze = torch.unsqueeze(x)
# adds a single dimensions

# permute rearranges the dimensions of a target tensors in a specified order
x_permuted =  torch.permute(10, 1)
x_orginal = torch.rand(size=(224, 224, 3))
# permute the orginial tnesor to rearrange the axis or dim order
x_perumte = torch.permute(2, 0, 1) # shifts axis 0 - > 1, 1 -> 2, 2 - > 0

print(f"pervious shape: {x_orginal.shape}")
print(f"new shape: {x_permuted.shape}")



In [ ]:
# selecting the data from tensors indexing
# indexing with pytorch is similar to indexing with numpy

# create a tensor
x = torch.arange(1, 10).reshpae(1, 3, 3)
x.shape
# let's index on tensor
x[0] # o dim
# index on middle bracket dim = 1
x[0, 0] # or x[0][0]
# index on most inner brack last dimension
x[0][0][0]
# you can also use ":" to select all of a target dimension
x[:, 0]
# get all values of 0th  and 1st dim a but only index of 1 of 2nd dimension
x[:, :, 1]
# get all values of 0 dim but only the 1 index value of 1st and 2nd dim
x[:, 1, 1]
# get index of 0 and 0th and 1st dim and all values of 2nd dim
x[0, 0, :]


In [ ]:
### PyTorch tensors & NumPy
# numpy is a popular scientific python numerical computing library
# and because of this, PyTorch has fuunctionality to interact with it
# data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
# PyTorch tensor -> NumPy -> torch.Tensor.numpy()

# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

array.dtype

# when converting from numpy -> pytotch reflects numpy's default datatype

# change the value of array, what will do this do to 'tensor'?
array += 1
array, tensor

# tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

numpy_tensor.dtype

#change the tensor, what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor



In [ ]:
# reproducbility trying to take random out of random
# in short how a neural network learns:
# start with random numbers -> tensor operations -> update random numbers to try and
# make them of the dat -> again -> again -> again..

# to reduce the randomness in neural networks and PyTorch comes the concept of a
# random seed
# what the random seed does is "flavour" the randomness.

# create two random tensors
random_tensor_A, random_tensor_B = torch.rand(3, 4), torch.rand(3, 4)
print(random_tensor_A ==  random_tensor_B)

# some random but reproducible tensors
# set the random seed
torch.manual_seed(42)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C == random_tensor_D)



In [ ]:
# running tensors and PyTorch obnjects on the GPUs (and making faster computations)
# GPUs = Fatser computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything fast
# getting a GPU
# easy use googel colab for a GPU
# use your own GPU
# use cloud computing - GCP, AWS, Azure
# check for GPu with PyTorch
# torch.cuda.isavaialable()
# device = "cuda"
device = "cuda" if torch.cuda.is_available() else "cpu"
# count number of devices
torch.cuda.device_count()

#putting tensors and models on the GPU - why?
# The reason we want our tensors ands models on the GPU is because using a GPU results in fatser omputations
# create a tensor default on GPU
tensor = torch.tensor([1, 2, 3])
print(tesnor, tensor.device)

# change to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

 # moving tensors back to cpu  , tenor on gpu can't tansform it to NumPy - NumPy does not work with GPU
 tensor_on_cpu = tensor_on_gpu.to("cpu") # or tensor_on_gpu.cpu().numpy()
 tensor_on_cpu


In [ ]:
# Excerises and extra curriculum
# random tensor shape 7, 7
